# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/sensors/radar_status.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/sensors/radar_status.proto',
  package='nio.ad.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n!common/sensors/radar_status.proto\x12\x0fnio.ad.messages\"\xcf\x01\n\x10RadarDiagnoseCAN\x12\x10\n\x08\x62lok_det\x18\x01 \x01(\x08\x12\x10\n\x08volt_low\x18\x02 \x01(\x08\x12\x11\n\tvolt_high\x18\x03 \x01(\x08\x12\x14\n\x0c\x61lign_incomp\x18\x04 \x01(\x08\x12\x13\n\x0binter_fault\x18\x05 \x01(\x08\x12\x17\n\x0f\x61lign_out_range\x18\x06 \x01(\x08\x12\x16\n\x0eivlid_data_adc\x18\x07 \x01(\x08\x12\x15\n\rloss_comm_adc\x18\x08 \x01(\x08\x12\x11\n\ttemp_high\x18\t \x01(\x08\"=\n\x11RadarActiveFaults\x12\x13\n\x0b\x61\x63t_fault_1\x18\x01 \x01(\x04\x12\x13\n\x0b\x61\x63t_fault_2\x18\x02 \x01(\x04\"U\n\x14RadarSDKActiveFaults\x12\x13\n\x0bsdk_fault_1\x18\x01 \x01(\x04\x12\x13\n\x0bsdk_fault_2\x18\x02 \x01(\x04\x12\x13\n\x0bsdk_fault_3\x18\x03 \x01(\x04\"\x85\x06\n\x10RadarFaultStatus\x12\x36\n\x0brad_fc_fail\x18\x01 \x01(\x0b\x32!.nio.ad.messages.RadarDiagnoseCAN\x12\x36\n\x0brad_fl_fail\x18\x02 \x01(\x0b\x32!.nio.ad.messages.RadarDiagnoseCAN\x12\x36\n\x0brad_fr_fail\x18\x03 \x01(\x0b\x32!.nio.ad.messages.RadarDiagnoseCAN\x12\x36\n\x0brad_rl_fail\x18\x04 \x01(\x0b\x32!.nio.ad.messages.RadarDiagnoseCAN\x12\x36\n\x0brad_rr_fail\x18\x05 \x01(\x0b\x32!.nio.ad.messages.RadarDiagnoseCAN\x12<\n\x10rad_fc_act_fault\x18\x06 \x01(\x0b\x32\".nio.ad.messages.RadarActiveFaults\x12<\n\x10rad_fl_act_fault\x18\x07 \x01(\x0b\x32\".nio.ad.messages.RadarActiveFaults\x12<\n\x10rad_fr_act_fault\x18\x08 \x01(\x0b\x32\".nio.ad.messages.RadarActiveFaults\x12<\n\x10rad_rl_act_fault\x18\t \x01(\x0b\x32\".nio.ad.messages.RadarActiveFaults\x12<\n\x10rad_rr_act_fault\x18\n \x01(\x0b\x32\".nio.ad.messages.RadarActiveFaults\x12@\n\x11rad_sdk_act_fault\x18\x0b \x01(\x0b\x32%.nio.ad.messages.RadarSDKActiveFaults\x12\x1a\n\x0epublish_ptp_ts\x18\xfb\xff\xff\xff\x01 \x01(\x04\x12\x18\n\x0cpublisher_id\x18\xfd\xff\xff\xff\x01 \x01(\t\x12\x13\n\x07\x63ounter\x18\xfe\xff\xff\xff\x01 \x01(\x04\x12\x16\n\npublish_ts\x18\xff\xff\xff\xff\x01 \x01(\x04')
)




_RADARDIAGNOSECAN = _descriptor.Descriptor(
  name='RadarDiagnoseCAN',
  full_name='nio.ad.messages.RadarDiagnoseCAN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blok_det', full_name='nio.ad.messages.RadarDiagnoseCAN.blok_det', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volt_low', full_name='nio.ad.messages.RadarDiagnoseCAN.volt_low', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volt_high', full_name='nio.ad.messages.RadarDiagnoseCAN.volt_high', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='align_incomp', full_name='nio.ad.messages.RadarDiagnoseCAN.align_incomp', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inter_fault', full_name='nio.ad.messages.RadarDiagnoseCAN.inter_fault', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='align_out_range', full_name='nio.ad.messages.RadarDiagnoseCAN.align_out_range', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ivlid_data_adc', full_name='nio.ad.messages.RadarDiagnoseCAN.ivlid_data_adc', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='loss_comm_adc', full_name='nio.ad.messages.RadarDiagnoseCAN.loss_comm_adc', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp_high', full_name='nio.ad.messages.RadarDiagnoseCAN.temp_high', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=262,
)


_RADARACTIVEFAULTS = _descriptor.Descriptor(
  name='RadarActiveFaults',
  full_name='nio.ad.messages.RadarActiveFaults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='act_fault_1', full_name='nio.ad.messages.RadarActiveFaults.act_fault_1', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='act_fault_2', full_name='nio.ad.messages.RadarActiveFaults.act_fault_2', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=325,
)


_RADARSDKACTIVEFAULTS = _descriptor.Descriptor(
  name='RadarSDKActiveFaults',
  full_name='nio.ad.messages.RadarSDKActiveFaults',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sdk_fault_1', full_name='nio.ad.messages.RadarSDKActiveFaults.sdk_fault_1', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sdk_fault_2', full_name='nio.ad.messages.RadarSDKActiveFaults.sdk_fault_2', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sdk_fault_3', full_name='nio.ad.messages.RadarSDKActiveFaults.sdk_fault_3', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=412,
)


_RADARFAULTSTATUS = _descriptor.Descriptor(
  name='RadarFaultStatus',
  full_name='nio.ad.messages.RadarFaultStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rad_fc_fail', full_name='nio.ad.messages.RadarFaultStatus.rad_fc_fail', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rad_fl_fail', full_name='nio.ad.messages.RadarFaultStatus.rad_fl_fail', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rad_fr_fail', full_name='nio.ad.messages.RadarFaultStatus.rad_fr_fail', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rad_rl_fail', full_name='nio.ad.messages.RadarFaultStatus.rad_rl_fail', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rad_rr_fail', full_name='nio.ad.messages.RadarFaultStatus.rad_rr_fail', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rad_fc_act_fault', full_name='nio.ad.messages.RadarFaultStatus.rad_fc_act_fault', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rad_fl_act_fault', full_name='nio.ad.messages.RadarFaultStatus.rad_fl_act_fault', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rad_fr_act_fault', full_name='nio.ad.messages.RadarFaultStatus.rad_fr_act_fault', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rad_rl_act_fault', full_name='nio.ad.messages.RadarFaultStatus.rad_rl_act_fault', index=8,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rad_rr_act_fault', full_name='nio.ad.messages.RadarFaultStatus.rad_rr_act_fault', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rad_sdk_act_fault', full_name='nio.ad.messages.RadarFaultStatus.rad_sdk_act_fault', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publish_ptp_ts', full_name='nio.ad.messages.RadarFaultStatus.publish_ptp_ts', index=11,
      number=536870907, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publisher_id', full_name='nio.ad.messages.RadarFaultStatus.publisher_id', index=12,
      number=536870909, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter', full_name='nio.ad.messages.RadarFaultStatus.counter', index=13,
      number=536870910, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publish_ts', full_name='nio.ad.messages.RadarFaultStatus.publish_ts', index=14,
      number=536870911, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=1188,
)

_RADARFAULTSTATUS.fields_by_name['rad_fc_fail'].message_type = _RADARDIAGNOSECAN
_RADARFAULTSTATUS.fields_by_name['rad_fl_fail'].message_type = _RADARDIAGNOSECAN
_RADARFAULTSTATUS.fields_by_name['rad_fr_fail'].message_type = _RADARDIAGNOSECAN
_RADARFAULTSTATUS.fields_by_name['rad_rl_fail'].message_type = _RADARDIAGNOSECAN
_RADARFAULTSTATUS.fields_by_name['rad_rr_fail'].message_type = _RADARDIAGNOSECAN
_RADARFAULTSTATUS.fields_by_name['rad_fc_act_fault'].message_type = _RADARACTIVEFAULTS
_RADARFAULTSTATUS.fields_by_name['rad_fl_act_fault'].message_type = _RADARACTIVEFAULTS
_RADARFAULTSTATUS.fields_by_name['rad_fr_act_fault'].message_type = _RADARACTIVEFAULTS
_RADARFAULTSTATUS.fields_by_name['rad_rl_act_fault'].message_type = _RADARACTIVEFAULTS
_RADARFAULTSTATUS.fields_by_name['rad_rr_act_fault'].message_type = _RADARACTIVEFAULTS
_RADARFAULTSTATUS.fields_by_name['rad_sdk_act_fault'].message_type = _RADARSDKACTIVEFAULTS
DESCRIPTOR.message_types_by_name['RadarDiagnoseCAN'] = _RADARDIAGNOSECAN
DESCRIPTOR.message_types_by_name['RadarActiveFaults'] = _RADARACTIVEFAULTS
DESCRIPTOR.message_types_by_name['RadarSDKActiveFaults'] = _RADARSDKACTIVEFAULTS
DESCRIPTOR.message_types_by_name['RadarFaultStatus'] = _RADARFAULTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RadarDiagnoseCAN = _reflection.GeneratedProtocolMessageType('RadarDiagnoseCAN', (_message.Message,), {
  'DESCRIPTOR' : _RADARDIAGNOSECAN,
  '__module__' : 'common.sensors.radar_status_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.RadarDiagnoseCAN)
  })
_sym_db.RegisterMessage(RadarDiagnoseCAN)

RadarActiveFaults = _reflection.GeneratedProtocolMessageType('RadarActiveFaults', (_message.Message,), {
  'DESCRIPTOR' : _RADARACTIVEFAULTS,
  '__module__' : 'common.sensors.radar_status_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.RadarActiveFaults)
  })
_sym_db.RegisterMessage(RadarActiveFaults)

RadarSDKActiveFaults = _reflection.GeneratedProtocolMessageType('RadarSDKActiveFaults', (_message.Message,), {
  'DESCRIPTOR' : _RADARSDKACTIVEFAULTS,
  '__module__' : 'common.sensors.radar_status_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.RadarSDKActiveFaults)
  })
_sym_db.RegisterMessage(RadarSDKActiveFaults)

RadarFaultStatus = _reflection.GeneratedProtocolMessageType('RadarFaultStatus', (_message.Message,), {
  'DESCRIPTOR' : _RADARFAULTSTATUS,
  '__module__' : 'common.sensors.radar_status_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.RadarFaultStatus)
  })
_sym_db.RegisterMessage(RadarFaultStatus)


# @@protoc_insertion_point(module_scope)
