# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/map_engine/hd_junction.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.map_engine import map_geometry_pb2 as common_dot_map__engine_dot_map__geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/map_engine/hd_junction.proto',
  package='nio.ad.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n#common/map_engine/hd_junction.proto\x12\x0fnio.ad.messages\x1a$common/map_engine/map_geometry.proto\"\x83\x01\n\nHdJunction\x12\n\n\x02id\x18\x01 \x01(\x04\x12,\n\x07surface\x18\x02 \x01(\x0b\x32\x1b.nio.ad.messages.MapPolygon\x12\x0f\n\x07lane_id\x18\x03 \x03(\x04\x12\x14\n\x0c\x63rosswalk_id\x18\x04 \x03(\x04\x12\x14\n\x0cstop_line_id\x18\x05 \x03(\x04\"D\n\x0eHdJunctionList\x12\x32\n\rjunction_list\x18\x01 \x03(\x0b\x32\x1b.nio.ad.messages.HdJunction')
  ,
  dependencies=[common_dot_map__engine_dot_map__geometry__pb2.DESCRIPTOR,])




_HDJUNCTION = _descriptor.Descriptor(
  name='HdJunction',
  full_name='nio.ad.messages.HdJunction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='nio.ad.messages.HdJunction.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='surface', full_name='nio.ad.messages.HdJunction.surface', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lane_id', full_name='nio.ad.messages.HdJunction.lane_id', index=2,
      number=3, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='crosswalk_id', full_name='nio.ad.messages.HdJunction.crosswalk_id', index=3,
      number=4, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stop_line_id', full_name='nio.ad.messages.HdJunction.stop_line_id', index=4,
      number=5, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=226,
)


_HDJUNCTIONLIST = _descriptor.Descriptor(
  name='HdJunctionList',
  full_name='nio.ad.messages.HdJunctionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='junction_list', full_name='nio.ad.messages.HdJunctionList.junction_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=296,
)

_HDJUNCTION.fields_by_name['surface'].message_type = common_dot_map__engine_dot_map__geometry__pb2._MAPPOLYGON
_HDJUNCTIONLIST.fields_by_name['junction_list'].message_type = _HDJUNCTION
DESCRIPTOR.message_types_by_name['HdJunction'] = _HDJUNCTION
DESCRIPTOR.message_types_by_name['HdJunctionList'] = _HDJUNCTIONLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HdJunction = _reflection.GeneratedProtocolMessageType('HdJunction', (_message.Message,), {
  'DESCRIPTOR' : _HDJUNCTION,
  '__module__' : 'common.map_engine.hd_junction_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.HdJunction)
  })
_sym_db.RegisterMessage(HdJunction)

HdJunctionList = _reflection.GeneratedProtocolMessageType('HdJunctionList', (_message.Message,), {
  'DESCRIPTOR' : _HDJUNCTIONLIST,
  '__module__' : 'common.map_engine.hd_junction_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.HdJunctionList)
  })
_sym_db.RegisterMessage(HdJunctionList)


# @@protoc_insertion_point(module_scope)
