# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/platform/mcu_proxy/mcu_field_common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/platform/mcu_proxy/mcu_field_common.proto',
  package='nio.ad.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n0common/platform/mcu_proxy/mcu_field_common.proto\x12\x0fnio.ad.messages\"\xa5\x01\n\x06\x46ields\x12\x30\n\x0bmcu_version\x18\x01 \x01(\x0b\x32\x1b.nio.ad.messages.McuVersion\x12\x36\n\x0evariant_config\x18\x02 \x01(\x0b\x32\x1e.nio.ad.messages.VariantConfig\x12\x31\n\x0chw_meta_info\x18\x03 \x01(\x0b\x32\x1b.nio.ad.messages.HwMetaInfo\"\xab\x01\n\nMcuVersion\x12\x17\n\x0fgit_commit_hash\x18\x01 \x01(\x0c\x12\x19\n\x11git_commit_author\x18\x02 \x01(\x0c\x12\x12\n\ngit_branch\x18\x03 \x01(\x0c\x12\x12\n\ngit_status\x18\x04 \x01(\x0c\x12\x12\n\nbuild_date\x18\x05 \x01(\x0c\x12\x15\n\rbuild_machine\x18\x06 \x01(\x0c\x12\x16\n\x0esw_part_number\x18\x07 \x01(\x0c\"\xaa\x01\n\rVariantConfig\x12\x46\n\x0fvehicle_project\x18\x01 \x01(\x0e\x32-.nio.ad.messages.VariantConfig.VehicleProject\"Q\n\x0eVehicleProject\x12\x1b\n\x17INVALID_VEHICLE_PROJECT\x10\x00\x12\t\n\x05\x46ORCE\x10\x01\x12\n\n\x06GEMINI\x10\x02\x12\x0b\n\x07PEGASUS\x10\x03\"\xa0\x01\n\nHwMetaInfo\x12\x16\n\x0ehw_part_number\x18\x01 \x01(\x0c\x12\x1a\n\x12hw_revision_number\x18\x02 \x01(\x0c\x12\x18\n\x10hw_serial_number\x18\x03 \x01(\x0c\x12\x18\n\x10hw_board_version\x18\x04 \x01(\x0c\x12\x18\n\x10mcu_chip_version\x18\x05 \x01(\x0c\x12\x10\n\x08ufs_type\x18\x06 \x01(\x0c*U\n\tFieldType\x12\x11\n\rINVALID_FILED\x10\x00\x12\x0f\n\x0bMCU_VERSION\x10\x01\x12\x12\n\x0eVARIANT_CONFIG\x10\x02\x12\x10\n\x0cHW_META_INFO\x10\x03')
)

_FIELDTYPE = _descriptor.EnumDescriptor(
  name='FieldType',
  full_name='nio.ad.messages.FieldType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_FILED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MCU_VERSION', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VARIANT_CONFIG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HW_META_INFO', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=747,
  serialized_end=832,
)
_sym_db.RegisterEnumDescriptor(_FIELDTYPE)

FieldType = enum_type_wrapper.EnumTypeWrapper(_FIELDTYPE)
INVALID_FILED = 0
MCU_VERSION = 1
VARIANT_CONFIG = 2
HW_META_INFO = 3


_VARIANTCONFIG_VEHICLEPROJECT = _descriptor.EnumDescriptor(
  name='VehicleProject',
  full_name='nio.ad.messages.VariantConfig.VehicleProject',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INVALID_VEHICLE_PROJECT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORCE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GEMINI', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PEGASUS', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=501,
  serialized_end=582,
)
_sym_db.RegisterEnumDescriptor(_VARIANTCONFIG_VEHICLEPROJECT)


_FIELDS = _descriptor.Descriptor(
  name='Fields',
  full_name='nio.ad.messages.Fields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mcu_version', full_name='nio.ad.messages.Fields.mcu_version', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='variant_config', full_name='nio.ad.messages.Fields.variant_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hw_meta_info', full_name='nio.ad.messages.Fields.hw_meta_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=235,
)


_MCUVERSION = _descriptor.Descriptor(
  name='McuVersion',
  full_name='nio.ad.messages.McuVersion',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='git_commit_hash', full_name='nio.ad.messages.McuVersion.git_commit_hash', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='git_commit_author', full_name='nio.ad.messages.McuVersion.git_commit_author', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='git_branch', full_name='nio.ad.messages.McuVersion.git_branch', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='git_status', full_name='nio.ad.messages.McuVersion.git_status', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_date', full_name='nio.ad.messages.McuVersion.build_date', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='build_machine', full_name='nio.ad.messages.McuVersion.build_machine', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sw_part_number', full_name='nio.ad.messages.McuVersion.sw_part_number', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=238,
  serialized_end=409,
)


_VARIANTCONFIG = _descriptor.Descriptor(
  name='VariantConfig',
  full_name='nio.ad.messages.VariantConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vehicle_project', full_name='nio.ad.messages.VariantConfig.vehicle_project', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _VARIANTCONFIG_VEHICLEPROJECT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=582,
)


_HWMETAINFO = _descriptor.Descriptor(
  name='HwMetaInfo',
  full_name='nio.ad.messages.HwMetaInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hw_part_number', full_name='nio.ad.messages.HwMetaInfo.hw_part_number', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hw_revision_number', full_name='nio.ad.messages.HwMetaInfo.hw_revision_number', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hw_serial_number', full_name='nio.ad.messages.HwMetaInfo.hw_serial_number', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hw_board_version', full_name='nio.ad.messages.HwMetaInfo.hw_board_version', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mcu_chip_version', full_name='nio.ad.messages.HwMetaInfo.mcu_chip_version', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ufs_type', full_name='nio.ad.messages.HwMetaInfo.ufs_type', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=585,
  serialized_end=745,
)

_FIELDS.fields_by_name['mcu_version'].message_type = _MCUVERSION
_FIELDS.fields_by_name['variant_config'].message_type = _VARIANTCONFIG
_FIELDS.fields_by_name['hw_meta_info'].message_type = _HWMETAINFO
_VARIANTCONFIG.fields_by_name['vehicle_project'].enum_type = _VARIANTCONFIG_VEHICLEPROJECT
_VARIANTCONFIG_VEHICLEPROJECT.containing_type = _VARIANTCONFIG
DESCRIPTOR.message_types_by_name['Fields'] = _FIELDS
DESCRIPTOR.message_types_by_name['McuVersion'] = _MCUVERSION
DESCRIPTOR.message_types_by_name['VariantConfig'] = _VARIANTCONFIG
DESCRIPTOR.message_types_by_name['HwMetaInfo'] = _HWMETAINFO
DESCRIPTOR.enum_types_by_name['FieldType'] = _FIELDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Fields = _reflection.GeneratedProtocolMessageType('Fields', (_message.Message,), {
  'DESCRIPTOR' : _FIELDS,
  '__module__' : 'common.platform.mcu_proxy.mcu_field_common_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.Fields)
  })
_sym_db.RegisterMessage(Fields)

McuVersion = _reflection.GeneratedProtocolMessageType('McuVersion', (_message.Message,), {
  'DESCRIPTOR' : _MCUVERSION,
  '__module__' : 'common.platform.mcu_proxy.mcu_field_common_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.McuVersion)
  })
_sym_db.RegisterMessage(McuVersion)

VariantConfig = _reflection.GeneratedProtocolMessageType('VariantConfig', (_message.Message,), {
  'DESCRIPTOR' : _VARIANTCONFIG,
  '__module__' : 'common.platform.mcu_proxy.mcu_field_common_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.VariantConfig)
  })
_sym_db.RegisterMessage(VariantConfig)

HwMetaInfo = _reflection.GeneratedProtocolMessageType('HwMetaInfo', (_message.Message,), {
  'DESCRIPTOR' : _HWMETAINFO,
  '__module__' : 'common.platform.mcu_proxy.mcu_field_common_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.HwMetaInfo)
  })
_sym_db.RegisterMessage(HwMetaInfo)


# @@protoc_insertion_point(module_scope)
