# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/nop/task_scheduler/service_area_point_cloud_map_request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common.map_engine import sd_map_pb2 as common_dot_map__engine_dot_sd__map__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/nop/task_scheduler/service_area_point_cloud_map_request.proto',
  package='nio.ad.messages',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\nDcommon/nop/task_scheduler/service_area_point_cloud_map_request.proto\x12\x0fnio.ad.messages\x1a\x1e\x63ommon/map_engine/sd_map.proto\"\xf4\x01\n\x1bServiceAreaPointCloudMapCmd\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x1d\n\x15power_swap_station_id\x18\x02 \x01(\t\x12\x38\n\x16power_swap_station_loc\x18\x03 \x01(\x0b\x32\x18.nio.ad.messages.Point2d\x12\x45\n\x07\x63ommand\x18\x04 \x01(\x0e\x32\x34.nio.ad.messages.ServiceAreaPointCloudMapCmd.Command\"\"\n\x07\x43ommand\x12\t\n\x05QUERY\x10\x00\x12\x0c\n\x08\x44OWNLOAD\x10\x01\"\xbf\x01\n\x1fServiceAreaPointCloudMapRequest\x12\x39\n\x03\x63md\x18\x01 \x01(\x0b\x32,.nio.ad.messages.ServiceAreaPointCloudMapCmd\x12\x1a\n\x0epublish_ptp_ts\x18\xfb\xff\xff\xff\x01 \x01(\x04\x12\x18\n\x0cpublisher_id\x18\xfd\xff\xff\xff\x01 \x01(\t\x12\x13\n\x07\x63ounter\x18\xfe\xff\xff\xff\x01 \x01(\x04\x12\x16\n\npublish_ts\x18\xff\xff\xff\xff\x01 \x01(\x04')
  ,
  dependencies=[common_dot_map__engine_dot_sd__map__pb2.DESCRIPTOR,])



_SERVICEAREAPOINTCLOUDMAPCMD_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='nio.ad.messages.ServiceAreaPointCloudMapCmd.Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QUERY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWNLOAD', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=332,
  serialized_end=366,
)
_sym_db.RegisterEnumDescriptor(_SERVICEAREAPOINTCLOUDMAPCMD_COMMAND)


_SERVICEAREAPOINTCLOUDMAPCMD = _descriptor.Descriptor(
  name='ServiceAreaPointCloudMapCmd',
  full_name='nio.ad.messages.ServiceAreaPointCloudMapCmd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='nio.ad.messages.ServiceAreaPointCloudMapCmd.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power_swap_station_id', full_name='nio.ad.messages.ServiceAreaPointCloudMapCmd.power_swap_station_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power_swap_station_loc', full_name='nio.ad.messages.ServiceAreaPointCloudMapCmd.power_swap_station_loc', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='nio.ad.messages.ServiceAreaPointCloudMapCmd.command', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVICEAREAPOINTCLOUDMAPCMD_COMMAND,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=366,
)


_SERVICEAREAPOINTCLOUDMAPREQUEST = _descriptor.Descriptor(
  name='ServiceAreaPointCloudMapRequest',
  full_name='nio.ad.messages.ServiceAreaPointCloudMapRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='nio.ad.messages.ServiceAreaPointCloudMapRequest.cmd', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publish_ptp_ts', full_name='nio.ad.messages.ServiceAreaPointCloudMapRequest.publish_ptp_ts', index=1,
      number=536870907, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publisher_id', full_name='nio.ad.messages.ServiceAreaPointCloudMapRequest.publisher_id', index=2,
      number=536870909, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='counter', full_name='nio.ad.messages.ServiceAreaPointCloudMapRequest.counter', index=3,
      number=536870910, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publish_ts', full_name='nio.ad.messages.ServiceAreaPointCloudMapRequest.publish_ts', index=4,
      number=536870911, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=560,
)

_SERVICEAREAPOINTCLOUDMAPCMD.fields_by_name['power_swap_station_loc'].message_type = common_dot_map__engine_dot_sd__map__pb2._POINT2D
_SERVICEAREAPOINTCLOUDMAPCMD.fields_by_name['command'].enum_type = _SERVICEAREAPOINTCLOUDMAPCMD_COMMAND
_SERVICEAREAPOINTCLOUDMAPCMD_COMMAND.containing_type = _SERVICEAREAPOINTCLOUDMAPCMD
_SERVICEAREAPOINTCLOUDMAPREQUEST.fields_by_name['cmd'].message_type = _SERVICEAREAPOINTCLOUDMAPCMD
DESCRIPTOR.message_types_by_name['ServiceAreaPointCloudMapCmd'] = _SERVICEAREAPOINTCLOUDMAPCMD
DESCRIPTOR.message_types_by_name['ServiceAreaPointCloudMapRequest'] = _SERVICEAREAPOINTCLOUDMAPREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceAreaPointCloudMapCmd = _reflection.GeneratedProtocolMessageType('ServiceAreaPointCloudMapCmd', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEAREAPOINTCLOUDMAPCMD,
  '__module__' : 'common.nop.task_scheduler.service_area_point_cloud_map_request_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.ServiceAreaPointCloudMapCmd)
  })
_sym_db.RegisterMessage(ServiceAreaPointCloudMapCmd)

ServiceAreaPointCloudMapRequest = _reflection.GeneratedProtocolMessageType('ServiceAreaPointCloudMapRequest', (_message.Message,), {
  'DESCRIPTOR' : _SERVICEAREAPOINTCLOUDMAPREQUEST,
  '__module__' : 'common.nop.task_scheduler.service_area_point_cloud_map_request_pb2'
  # @@protoc_insertion_point(class_scope:nio.ad.messages.ServiceAreaPointCloudMapRequest)
  })
_sym_db.RegisterMessage(ServiceAreaPointCloudMapRequest)


# @@protoc_insertion_point(module_scope)
