# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rospy_message_converter/AccrPedalInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class AccrPedalInfo(genpy.Message):
  _md5sum = "1a951a4e355235d4a1364524c79e3574"
  _type = "rospy_message_converter/AccrPedalInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 EfcPosnVld
float32 EfcPosn
int32 ActPosnVld
float32 ActPosn
bool PedlOvrd
uint64 timestamp_ptp_ns
"""
  __slots__ = ['EfcPosnVld','EfcPosn','ActPosnVld','ActPosn','PedlOvrd','timestamp_ptp_ns']
  _slot_types = ['int32','float32','int32','float32','bool','uint64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       EfcPosnVld,EfcPosn,ActPosnVld,ActPosn,PedlOvrd,timestamp_ptp_ns

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(AccrPedalInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.EfcPosnVld is None:
        self.EfcPosnVld = 0
      if self.EfcPosn is None:
        self.EfcPosn = 0.
      if self.ActPosnVld is None:
        self.ActPosnVld = 0
      if self.ActPosn is None:
        self.ActPosn = 0.
      if self.PedlOvrd is None:
        self.PedlOvrd = False
      if self.timestamp_ptp_ns is None:
        self.timestamp_ptp_ns = 0
    else:
      self.EfcPosnVld = 0
      self.EfcPosn = 0.
      self.ActPosnVld = 0
      self.ActPosn = 0.
      self.PedlOvrd = False
      self.timestamp_ptp_ns = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_ififBQ().pack(_x.EfcPosnVld, _x.EfcPosn, _x.ActPosnVld, _x.ActPosn, _x.PedlOvrd, _x.timestamp_ptp_ns))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.EfcPosnVld, _x.EfcPosn, _x.ActPosnVld, _x.ActPosn, _x.PedlOvrd, _x.timestamp_ptp_ns,) = _get_struct_ififBQ().unpack(str[start:end])
      self.PedlOvrd = bool(self.PedlOvrd)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_ififBQ().pack(_x.EfcPosnVld, _x.EfcPosn, _x.ActPosnVld, _x.ActPosn, _x.PedlOvrd, _x.timestamp_ptp_ns))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 25
      (_x.EfcPosnVld, _x.EfcPosn, _x.ActPosnVld, _x.ActPosn, _x.PedlOvrd, _x.timestamp_ptp_ns,) = _get_struct_ififBQ().unpack(str[start:end])
      self.PedlOvrd = bool(self.PedlOvrd)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_ififBQ = None
def _get_struct_ififBQ():
    global _struct_ififBQ
    if _struct_ififBQ is None:
        _struct_ififBQ = struct.Struct("<ififBQ")
    return _struct_ififBQ
