# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rospy_message_converter/ACMFaultInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ACMFaultInfo(genpy.Message):
  _md5sum = "45fe979743201ef8e52b3dd417d5a497"
  _type = "rospy_message_converter/ACMFaultInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool CHS1_ACM_01_MsgError
bool CHS1_ACM_02_MsgError
bool CHS1_ACM_03_MsgError
bool CHS1_ACM_LossCom
"""
  __slots__ = ['CHS1_ACM_01_MsgError','CHS1_ACM_02_MsgError','CHS1_ACM_03_MsgError','CHS1_ACM_LossCom']
  _slot_types = ['bool','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       CHS1_ACM_01_MsgError,CHS1_ACM_02_MsgError,CHS1_ACM_03_MsgError,CHS1_ACM_LossCom

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ACMFaultInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.CHS1_ACM_01_MsgError is None:
        self.CHS1_ACM_01_MsgError = False
      if self.CHS1_ACM_02_MsgError is None:
        self.CHS1_ACM_02_MsgError = False
      if self.CHS1_ACM_03_MsgError is None:
        self.CHS1_ACM_03_MsgError = False
      if self.CHS1_ACM_LossCom is None:
        self.CHS1_ACM_LossCom = False
    else:
      self.CHS1_ACM_01_MsgError = False
      self.CHS1_ACM_02_MsgError = False
      self.CHS1_ACM_03_MsgError = False
      self.CHS1_ACM_LossCom = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.CHS1_ACM_01_MsgError, _x.CHS1_ACM_02_MsgError, _x.CHS1_ACM_03_MsgError, _x.CHS1_ACM_LossCom))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.CHS1_ACM_01_MsgError, _x.CHS1_ACM_02_MsgError, _x.CHS1_ACM_03_MsgError, _x.CHS1_ACM_LossCom,) = _get_struct_4B().unpack(str[start:end])
      self.CHS1_ACM_01_MsgError = bool(self.CHS1_ACM_01_MsgError)
      self.CHS1_ACM_02_MsgError = bool(self.CHS1_ACM_02_MsgError)
      self.CHS1_ACM_03_MsgError = bool(self.CHS1_ACM_03_MsgError)
      self.CHS1_ACM_LossCom = bool(self.CHS1_ACM_LossCom)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4B().pack(_x.CHS1_ACM_01_MsgError, _x.CHS1_ACM_02_MsgError, _x.CHS1_ACM_03_MsgError, _x.CHS1_ACM_LossCom))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 4
      (_x.CHS1_ACM_01_MsgError, _x.CHS1_ACM_02_MsgError, _x.CHS1_ACM_03_MsgError, _x.CHS1_ACM_LossCom,) = _get_struct_4B().unpack(str[start:end])
      self.CHS1_ACM_01_MsgError = bool(self.CHS1_ACM_01_MsgError)
      self.CHS1_ACM_02_MsgError = bool(self.CHS1_ACM_02_MsgError)
      self.CHS1_ACM_03_MsgError = bool(self.CHS1_ACM_03_MsgError)
      self.CHS1_ACM_LossCom = bool(self.CHS1_ACM_LossCom)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4B = None
def _get_struct_4B():
    global _struct_4B
    if _struct_4B is None:
        _struct_4B = struct.Struct("<4B")
    return _struct_4B
