# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rospy_message_converter/DowngradeLaneSegment.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class DowngradeLaneSegment(genpy.Message):
  _md5sum = "4568a7bbcf2ce4c9d8536bf2e2cd258b"
  _type = "rospy_message_converter/DowngradeLaneSegment"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 ad_mode_type
float64 start_s
float64 end_s
int32 info_value
int32 dynamic_info
int32 road_scenario_type
"""
  __slots__ = ['ad_mode_type','start_s','end_s','info_value','dynamic_info','road_scenario_type']
  _slot_types = ['int32','float64','float64','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ad_mode_type,start_s,end_s,info_value,dynamic_info,road_scenario_type

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(DowngradeLaneSegment, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ad_mode_type is None:
        self.ad_mode_type = 0
      if self.start_s is None:
        self.start_s = 0.
      if self.end_s is None:
        self.end_s = 0.
      if self.info_value is None:
        self.info_value = 0
      if self.dynamic_info is None:
        self.dynamic_info = 0
      if self.road_scenario_type is None:
        self.road_scenario_type = 0
    else:
      self.ad_mode_type = 0
      self.start_s = 0.
      self.end_s = 0.
      self.info_value = 0
      self.dynamic_info = 0
      self.road_scenario_type = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_i2d3i().pack(_x.ad_mode_type, _x.start_s, _x.end_s, _x.info_value, _x.dynamic_info, _x.road_scenario_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.ad_mode_type, _x.start_s, _x.end_s, _x.info_value, _x.dynamic_info, _x.road_scenario_type,) = _get_struct_i2d3i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_i2d3i().pack(_x.ad_mode_type, _x.start_s, _x.end_s, _x.info_value, _x.dynamic_info, _x.road_scenario_type))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.ad_mode_type, _x.start_s, _x.end_s, _x.info_value, _x.dynamic_info, _x.road_scenario_type,) = _get_struct_i2d3i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i2d3i = None
def _get_struct_i2d3i():
    global _struct_i2d3i
    if _struct_i2d3i is None:
        _struct_i2d3i = struct.Struct("<i2d3i")
    return _struct_i2d3i
