# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from rospy_message_converter/Overlap.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Overlap(genpy.Message):
  _md5sum = "f938a7fd491e0407f2bfdf5081a70605"
  _type = "rospy_message_converter/Overlap"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint64 self_id
uint64 other_id
int32 type
float64 start_s
float64 end_s
"""
  __slots__ = ['self_id','other_id','type','start_s','end_s']
  _slot_types = ['uint64','uint64','int32','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       self_id,other_id,type,start_s,end_s

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Overlap, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.self_id is None:
        self.self_id = 0
      if self.other_id is None:
        self.other_id = 0
      if self.type is None:
        self.type = 0
      if self.start_s is None:
        self.start_s = 0.
      if self.end_s is None:
        self.end_s = 0.
    else:
      self.self_id = 0
      self.other_id = 0
      self.type = 0
      self.start_s = 0.
      self.end_s = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Qi2d().pack(_x.self_id, _x.other_id, _x.type, _x.start_s, _x.end_s))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.self_id, _x.other_id, _x.type, _x.start_s, _x.end_s,) = _get_struct_2Qi2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Qi2d().pack(_x.self_id, _x.other_id, _x.type, _x.start_s, _x.end_s))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 36
      (_x.self_id, _x.other_id, _x.type, _x.start_s, _x.end_s,) = _get_struct_2Qi2d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Qi2d = None
def _get_struct_2Qi2d():
    global _struct_2Qi2d
    if _struct_2Qi2d is None:
        _struct_2Qi2d = struct.Struct("<2Qi2d")
    return _struct_2Qi2d
